import {
  SiApollographql,
  SiDocker,
  SiElectron,
  SiFastapi,
  SiFlask,
  SiGit,
  SiGnubash,
  SiGo,
  SiGraphql,
  SiJavascript,
  SiJquery,
  SiJsonwebtokens,
  SiKeras,
  SiKotlin,
  SiLaravel,
  SiMicrosoftazure,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPhp,
  SiPostgresql,
  SiPython,
  SiReact,
  SiRedis,
  SiScikitlearn,
  SiSelenium,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
} from 'react-icons/si';

const badges = {
  tailwind: {
    backgroundColor: 'bg-sky-500',
    textColor: 'text-white',
    icon: <SiTailwindcss />,
    name: 'Tailwind CSS',
  },
  react: {
    backgroundColor: 'bg-sky-400',
    textColor: 'text-white',
    icon: <SiReact />,
    name: 'React',
  },
  python: {
    backgroundColor: 'bg-blue-900',
    textColor: 'text-white',
    icon: <SiPython />,
    name: 'Python',
  },
  php: {
    backgroundColor: 'bg-indigo-400',
    textColor: 'text-white',
    icon: <SiPhp />,
    name: 'PHP',
  },
  next: {
    backgroundColor: 'bg-black',
    textColor: 'text-white',
    icon: <SiNextdotjs />,
    name: 'Next.js',
  },
  mysql: {
    backgroundColor: 'bg-[#4479a1]',
    textColor: 'text-white',
    icon: <SiMysql />,
    name: 'MySQL',
  },
  kotlin: {
    backgroundColor: 'bg-purple-600',
    textColor: 'text-white',
    icon: <SiKotlin />,
    name: 'Kotlin',
  },
  keras: {
    backgroundColor: 'bg-red-600',
    textColor: 'text-white',
    icon: <SiKeras />,
    name: 'Keras',
  },
  javascript: {
    backgroundColor: 'bg-yellow-500',
    textColor: 'text-black',
    icon: <SiJavascript />,
    name: 'Javascript (ES9)',
  },
  go: {
    backgroundColor: 'bg-sky-700',
    textColor: 'text-white',
    icon: <SiGo />,
    name: 'Go',
  },
  git: {
    backgroundColor: 'bg-red-500',
    textColor: 'text-white',
    icon: <SiGit />,
    name: 'Git',
  },
  flask: {
    backgroundColor: 'bg-white',
    textColor: 'text-black',
    icon: <SiFlask />,
    name: 'Flask',
  },
  typescript: {
    backgroundColor: 'bg-sky-700',
    textColor: 'text-white',
    icon: <SiTypescript />,
    name: 'Typescript',
  },
  node: {
    backgroundColor: 'bg-green-700',
    textColor: 'text-white',
    icon: <SiNodedotjs />,
    name: 'Node.js',
  },
  jquery: {
    backgroundColor: 'bg-sky-700',
    textColor: 'text-white',
    icon: <SiJquery />,
    name: 'jQuery',
  },
  selenium: {
    backgroundColor: 'bg-green-600',
    textColor: 'text-white',
    icon: <SiSelenium />,
    name: 'Selenium',
  },
  jwt: {
    backgroundColor: 'bg-purple-500',
    textColor: 'text-white',
    icon: <SiJsonwebtokens />,
    name: 'JWT',
  },
  graphql: {
    backgroundColor: 'bg-pink-700',
    textColor: 'text-white',
    icon: <SiGraphql />,
    name: 'GraphQL',
  },
  apollo: {
    backgroundColor: 'bg-indigo-600',
    textColor: 'text-white',
    icon: <SiApollographql />,
    name: 'Apollo GraphQL',
  },
  mongodb: {
    backgroundColor: 'bg-green-500',
    textColor: 'text-white',
    icon: <SiMongodb />,
    name: 'MongoDB',
  },
  tensorflow: {
    backgroundColor: 'bg-orange-600',
    textColor: 'text-white',
    icon: <SiTensorflow />,
    name: 'Tensorflow',
  },
  sklearn: {
    backgroundColor: 'bg-orange-400',
    textColor: 'text-white',
    icon: <SiScikitlearn />,
    name: 'scikit-learn',
  },
  fastapi: {
    backgroundColor: 'bg-green-700',
    textColor: 'text-white',
    icon: <SiFastapi />,
    name: 'FastAPI',
  },
  laravel: {
    backgroundColor: 'bg-red-600',
    textColor: 'text-white',
    icon: <SiLaravel />,
    name: 'Laravel',
  },
  postgresql: {
    backgroundColor: 'bg-[#336791]',
    textColor: 'text-white',
    icon: <SiPostgresql />,
    name: 'PostgreSQL',
  },
  azure: {
    backgroundColor: 'bg-[#0078d4]',
    textColor: 'text-white',
    icon: <SiMicrosoftazure />,
    name: 'Azure',
  },
  bash: {
    backgroundColor: 'bg-black',
    textColor: 'text-white',
    icon: <SiGnubash />,
    name: 'Bash',
  },
  reactNative: {
    backgroundColor: 'bg-sky-400',
    textColor: 'text-white',
    icon: <SiReact />,
    name: 'React Native',
  },
  docker: {
    backgroundColor: 'bg-blue-400',
    textColor: 'text-white',
    icon: <SiDocker />,
    name: 'Docker',
  },
  redis: {
    backgroundColor: 'bg-red-500',
    textColor: 'text-white',
    icon: <SiRedis />,
    name: 'Redis',
  },
  electron: {
    backgroundColor: 'bg-black',
    textColor: 'text-white',
    icon: <SiElectron />,
    name: 'Electron',
  },
};

export default badges;
